name: Recent Changes refresh

on: 
  schedule:  
    - cron:  '20 12 * * *'
  push:
    branches:
      - main
jobs:
  Running_R_scripts:
    runs-on: ubuntu-20.04 
    defaults:
      run:
        working-directory: weblate/Recent Changes
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    - name: Print working directory
      run: pwd
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Install Packages
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("stringr")'
        Rscript -e 'install.packages("readr")' 
        Rscript -e 'install.packages("curl")' 
        Rscript -e 'install.packages("lubridate")' 
        
        
    - name: Run R scripts
      run: | 
        Rscript "Recent changes.R"
      
    - name: Configure 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit and Push Changes
      run: |
        git pull origin main
        git add .
        git commit -m "Updated changes Csv"
        git push
