# Hourly scraping
name: Creation of CSV 

# Controls when the action will run.
on:
  push:
    branches: main
    paths:
      - 'translation_status.R'
  schedule:
    - cron: '0 0 * * *'

jobs: 
  Messages:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with: 
        repository: r-devel/r-svn
        path: r-svn
    - uses: r-lib/actions/setup-r@v2
    - name: Install packages
      run: |
        R -e 'install.packages("ISOcodes")'
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("purrr")'
        R -e 'install.packages("readr")'
        R -e 'install.packages("tidyr")'
        R -e 'install.packages("utf8")'
        R -e 'install.packages("withr")'
        R -e 'install.packages("stringr")'
    # Run R script
    - name: Scrape
      run: Rscript translation_status.R
    - name: Commit and Push Any Changes
      run: |
        git pull
        git add *.csv
        if ! git diff-index --quiet HEAD; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update r-devel message status"
          git push
        fi
