name: Dashboard Refresh

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  refresh-the-dashboard:
    runs-on: windows-latest
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Render Rmarkdown
      run: |
        Rscript -e 'rmarkdown::render("https://github.com/shrish-shete20/translations/blob/main/index.Rmd.Rmd")'

