
name: Main Dashboard Refresh

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-20.04  
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages("flexdashboard")'
        Rscript -e 'install.packages("crosstalk")'
        Rscript -e 'install.packages("htmltools")'
        Rscript -e 'install.packages("reactable")'
        
    - name: Render my document to all types
     run: rm -rf index_files && Rscript -e 'rmarkdown::render("index.Rmd")'
    - name: Configure 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit and Push Changes
      run: |
        git pull origin main
        git add .
        git commit -m "CSS updated"
        git push

