
name: Dashboard Refresh

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-20.04  
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
      with: 
        ref: 'main'
    - name: Render document
      uses: lc5415/rmarkdown-action@v1
      with:
        input_file: index.Rmd
	      run-name: html_document
   
