
name: Dashboard Refresh

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-20.04  
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
      with: 
        ref: 'main'
    - name: Install packages
      run: Rscript -e 'install.packages("rmarkdown", repos = "http://cran.rstudio.com/", ErrorAction="Continue")'
    - name: Render Rmarkdown
      run: bash ./bash/render_dashboard.sh "shrish-shete20" "sheteshrish1203@gmail.com"
   
