
name: Dashboard Refresh

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-20.04  
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - uses: r-lib/actions/setup-tinytex@v1
    - name: Install rmarkdown
      run: Rscript -e 'install.packages("rmarkdown")'
    - name: Render my document to all types
      run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'
   
